peyton-lalli/swe5-project-backend

.github/workflow/node-deploy.yml, performance-t3-backend.service
Added the secrets to GitHub as well as changed the node-deploy.yaml action and the backend service to deploy to AWS.
This will allow us to push the code up to the AWS server when we close a pull request on the dev or the main branch. On the final push to the main, we can change the code to only push the main branch.
I created a new project in the Google Console to get the google OAuth credentials to allow for google authentication on the front and backend.
=> Adds secrets, service, and action to upload to AWS

.github/workflow/node-deploy.yml
Removed line that turned the workflow off.
=> turned on the workflow

app.js
Change the port so that the api will run on the server
=> Update the port to run on

.github/workflows/node-deploy.yml, app.js, package.json
Change the service to get it to run on the server during the GitHub action.
=> Change the service

package.json
Fixes the package JSON file so that it will copy all of the files.
=> Backend service

package.json
Fix the bundle to move the right files into the AWS server.
=> Fix the bundle

config/prod.db.config.js, package.json
Add the Authorization folder to the list of files to copy to the server and fixes the syntax in the dbConfig file.
=> Copy the authorization folder and fix the dbConfig

controllers/auth.controller.js
Sends the role back with the login request to know where to send the user.
Defaults to the student view if the user has no role.
=> Sends role with login

controllers/composers.controller.js, package.json, routes/routes.js
Fix the npm bundle after removing the file handling files.
Adds some error checking on the routes.
=> Route edits nl

config/prod.db.config.js, package.json
Changed the prod.db.config file to match the Github secrets format.
Changed the package JSON to create the .env file on the server.
=> Prod db nl

controllers/instruments.controller.js, models/instruments.model.js, models/studentInstruments.model.js
Had to fix a slight typo where the database wasn't building becuase some things were plural but other were singular.
=> Fix the naming convention

controllers/auth.controller.js
This edits the authentication controller to check for an active session
for a user before creating a session. This should allow for a user to stay logged in
instead of a new login every time.
=> Edit to the authentication controller

controllers/auth.controller.js, models/users.model.js
Creates a column in the User table for the user's google picture.
This also changes the authentication controller to send the picture to the frontend when the user logs in so that it can be used there as well and stored in Pinia.
=> Adds the user's google picture to the database

controllers/instructors.controller.js, routes/routes.js
Added ability to find instructor by instructorId
=> Add Find Instructor by instructorId

controllers/eventsongs.controller.js, controllers/pieces.controller.js, models/foreignkeys.js, routes/routes.js
Edit to the event songs foreign keys to be the event sign up instead of the base event.
=> Event model edits nl

controllers/event.controller.js, controllers/eventsignup.controller.js, models/event.model.js, models/foreignkeys.js, routes/routes.js
Edit the Event model to change to just date and not date time 
Edit the Event Controller to remove the foreign key and change to get the date and not date time 
Edit the Event Sign Up Controller to add the Ensemble ID foreign key and add a function to get the ensemble id 
Edit the foreign keys to remove the foreign keys from event table and add an ensemble foreign key to event sign up 
Add new function for event sign up to the routes
=> Edit the Event Model and Controllers

controllers/studentinfo.controller.js, routes/routes.js
Edits the student info controller to allow us to get a list of students based on their instructor Id
=> Edit student info Controller

controllers/composers.controller.js, controllers/eventsongs.controller.js, controllers/pieces.controller.js, routes/routes.js
Just some fixes to allow the new stores to work well, pretty self-explanatory here.
=> Fixes to Controllers for New Stores and Event Signup

controllers/roles.controller.js, controllers/userrole.controller.js, controllers/users.controller.js, models/foreignkeys.js, models/index.js, models/roles.model.js, models/userrole.model.js, routes/routes.js
This creates a roles and a userrole table.
- The roles table will hold the different roles that users can have, i.e. Student, Faculty, Admin. 
- The userrole table will hold the userid and the roleid. 
This will allow us to put multiple roles on one user incase someone is an admin and a faculty member. 
There are also some route edits to make the different routing work to actually use the tables.
=> Changes the ways roles work in the database

models/foreignkeys.js
- Removes the userrole foreign key from the user table
=> Remove foreign key

controllers/auth.controller.js
Returns new array of user roles after login, instead of just single role.
=> Get New Roles System Working

controllers/auth.controller.js
This assigns the user a role when they first log in based on their email.
- If they have an @oc.edu email they are assigned the role of faculty
- If they have an @eagles.oc.edu they are assigned the role of student
Also messed around with how the roles were sent to the front end but realized why Ethan did it the way he did and reverted it back. Did change the variable name of the db to userrole instead of userroles though since it is not plural on the backend model and controller.
=> Assigns role at new login

controllers/userrole.controller.js, routes/routes.js
Fixes the userrole controller to make sure there is no 500 error to the front end.
=> Fixes the userrole controller

controllers/eventsongs.controller.js, routes/routes.js
Makes a few changes to get frontend event signup edit working.
EventSongs was missing the entirety of .update .... yet it was in the frontend controller.
=> Update Backend for Event Signups Edit

models/availability.model.js, models/composers.model.js, models/critiques.model.js, models/ensemble.model.js, models/event.model.js, models/eventsignup.model.js, models/eventsongs.model.js, models/eventtime.model.js, models/instructors.model.js, models/instruments.model.js, models/members.model.js, models/pieces.model.js, models/repertoire.model.js, models/requirements.model.js, models/roles.model.js, models/session.model.js, models/studentinfo.model.js, models/studentinstruments.model.js, models/userrole.model.js, models/users.model.js
Adds the timestamp column to the backend. This adds a createdAt and updatedAt column to the backend.
- The createdAt column is set when the row is created
- The updatedAt column is set when the row is changed in any way
=> Add a timestamp to the backend

controllers/accompanists.controller.js, controllers/studentaccompanist.controller.js, controllers/studentinstructor.controller.js, models/accompanists.model.js, models/foreignkeys.js, models/index.js, models/studentaccompanist.model.js, models/studentinstructor.model.js, routes/routes.js
Adds an accompanist and instructor link table to the database. This table will be used to link accompanists and instructors to a particular student so that a student can have multiple accompanists and instructors.
- Added an accompanist table that only has an ID for now
- Added a studentinstructor table with an id and two foreign keys for the studentinfo table and the instructors table
- Added a studentaccompanist table with an id and two foreign keys for the studentinfo table and the accompanist table
- Added a controller for the studentinstructor table that has a findStudent method and a findInstructor method
- Added a controller for the studentaccompanist table that has a findStudent method and a findAccompanist method
We can add more methods as needed.
We can also change the …
=> Adds accompanist and instructor link table

models/foreignkeys.js
Changes the foreign keys in both the eventsignup and the critique tables.
Critique table:
- Changed the foreign key from eventId to eventsignupId
Eventsignup table:
- Added a foreign key for instructorId and accompanistId
=> Edit the eventsignup and critique

controllers/accompanists.controller.js, controllers/eventsignup.controller.js, controllers/repertoire.controller.js, controllers/studentaccompanist.controller.js, controllers/studentinfo.controller.js, controllers/studentinstructor.controller.js, controllers/studentinstruments.controller.js, controllers/students.controller.js, models/foreignkeys.js, models/index.js, models/students.model.js, routes/routes.js, utils/students.js
Renames studentinfos table to students, to be continuous with instructors and accompanists
Adds utils folder, and the students.js util for getAllInfo
New Student userRoleInfo Structure
I've put an example of the structure below. I've updated most of the places it's used, but there is likely to be issues. It is very similar to how it used to be, so any changes should be really quick and easy.
```
{
"studentId": 1,
"level": 3,
"major": "Vocal Music",
"classification": "Senior",
"semesters": 8,
"memberId": null,
"requirementId": null,
"createdAt": null,
"updatedAt": null,
"instructors": [
{
"studentinstructorId": 1,
"instructorId": 1,
"title": "Private Instructor",
"userId": 2,
"email": "nathan.lalli@eagles.oc.edu",
"fName": "Nathan",
"lName": "Lalli",
"picture": …
```
=> Add New Student Functions

controllers/eventsignupjuror.controller.js, models/eventsignupjuror.model.js, models/foreignkeys.js, models/index.js, routes/routes.js
This adds a table called eventsignupjuror that will keep track of what Instructors are being a juror at a specific event sign up.
- Adds a model for the table
- Adds two foreign keys for the table
- Adds a controller for the table
- Adds the controller to the routes
=> Add Event Sign Up Juror Table

controllers/studentaccompanist.controller.js, controllers/studentinstructor.controller.js, routes/routes.js
Adds functions to get all students for instructors and accompanists.
- Adds function to studentinstructor to get all students for an instructor's id
- Adds function to studentaccompanist to get all students for an accompanist's id
- Adds both new functions to the routes
=> Add functions to get students

.github/workflows/node-deploy.yml
=> Fix deploy?

.github/workflows/node-deploy.yml
=> Fix deploy again

controllers/accompanists.controller.js, controllers/eventsignup.controller.js, controllers/eventsongs.controller.js, controllers/instruments.controller.js, controllers/studentinstruments.controller.js, controllers/students.controller.js, routes/routes.js
This edits a lot of the controllers to add functionality to some of the adding a critique page.
- Edits the accompanist controller to give the userId
- Edits the eventsignup controller to get on by the Id
- Edits the eventsongs controller moving the code to fit other format
- Edits the instrument controller to get one based on the id
- Edits the student instrument controller to get one based on the Id
- Edits the student controller to get a student based on their id
- Edits the routes to add all of the new functions
=> Edit to Controllers

controllers/accompanists.controller.js, controllers/instructors.controller.js, controllers/students.controller.js, routes/routes.js
This edits the backend controllers so that we can make less backend calls
- Edits the accompanist controller to include the name and picture from the user model
- Edits the instructor controller to include the name and picture from the user model
- Edits the student controller to include the name and picture from the user model
- Adds a function to the student controller that returns all of their repertoires along with all the pieces and data about them
- Edits the route to add the new function
=> Edit Controllers to Make less Calls

package-lock.json, package.json
Attempting to fix deploy by updating outdated packages.
=> Update Outdated Packages

utils/students.js
Just adds repId to pieces in students
=> Adds reps to pieces

controllers/accompanists.controller.js, models/foreignkeys.js, routes/routes.js, utils/accompanist.js, utils/students.js
Adds ability for an accompanist to add their availability for a signup, and for timeslots on a signup for a student to filter by that availability mixed with the instructor.
Also adds the accompanist dashboard, as I had to have it to get started on this task that needed to get done.
Also moves some logic for the instructor and accompanist getAll functions to the backend out of the frontend.
Frontend PR for this too.
=> Add Accompanist Availability for Event Signup

models/foreignkeys.js, utils/events.js
Adds jurors to critiques database and to events call for each sign up. 
Faculty critique creation needs to add juror id to critiques database now.
=> add-event-items-ld

models/critiques.model.js, utils/events.js
This helps with critique items for an event.
=> Fixed more event stuff

.gitignore, gmail/composer.js, gmail/gmail.js, models/critiques.model.js, models/foreignkeys.js, models/gmailtokens.model.js, models/index.js, package-lock.json, package.json, routes/routes.js, utils/gmailtokens.js
This adds functionality to send emails from the backend. There are currently two function to send emails and they are inside of the composer.js file
Send Notification
- This send a notification that a critique has been done for a student on a an event
Send Message
- This allows someone to send a custom message and subject to a custom list of students that are all bcc'ed for privacy
This is kind of piece mealed together from different documentation that I found because no one has documentation for the exact way that I was trying to do it because I was trying to keep it secure and make it work without saving a file to the backend and letting it work for more than one person.
In order to get this to work locally, you will need to add the gmail api client credentials to your .env file, but …
=> Add Functionality to Send Emails

package.json
Had to edit the run script in the package JSON file to copy the gmail file to the server
=> Edit Run Script

controllers/critiques.controller.js
Adds the eventsignupjurorId to the create function.
=> Edit the create for critiques

controllers/pieces.controller.js, models/pieces.model.js
=> Fix to Make Student Repertoire Edit work
